// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmrmwmRpkK2cPOLdKHaRSq8STkWRtVqaA',
    appId: '1:132080073709:web:3759376b13eeedc87885e4',
    messagingSenderId: '132080073709',
    projectId: 'glasses-store-7dc14',
    authDomain: 'glasses-store-7dc14.firebaseapp.com',
    storageBucket: 'glasses-store-7dc14.firebasestorage.app',
    measurementId: 'G-VGQKQE3LTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXaXY5XFg-QsN4r1ktaZOqTMB_iH5j-14',
    appId: '1:132080073709:android:a8766fe05ada7ce37885e4',
    messagingSenderId: '132080073709',
    projectId: 'glasses-store-7dc14',
    storageBucket: 'glasses-store-7dc14.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQKtLLe0KE250eruDSkq3nFODLosXnLSc',
    appId: '1:132080073709:ios:8d4a3c78494247a17885e4',
    messagingSenderId: '132080073709',
    projectId: 'glasses-store-7dc14',
    storageBucket: 'glasses-store-7dc14.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQKtLLe0KE250eruDSkq3nFODLosXnLSc',
    appId: '1:132080073709:ios:8d4a3c78494247a17885e4',
    messagingSenderId: '132080073709',
    projectId: 'glasses-store-7dc14',
    storageBucket: 'glasses-store-7dc14.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmrmwmRpkK2cPOLdKHaRSq8STkWRtVqaA',
    appId: '1:132080073709:web:e8ba221367d8259a7885e4',
    messagingSenderId: '132080073709',
    projectId: 'glasses-store-7dc14',
    authDomain: 'glasses-store-7dc14.firebaseapp.com',
    storageBucket: 'glasses-store-7dc14.firebasestorage.app',
    measurementId: 'G-220BK3TQ2F',
  );

}